// System constants for BhumiPatra Backend

export const ROLES = {
  DIGITIZATION_OPERATOR: 'DIGITIZATION_OPERATOR',
  VERIFICATION_OFFICER: 'VERIFICATION_OFFICER',
  ADMIN: 'ADMIN',
};

export const PROCESSING_STATUS = {
  PENDING: 'PENDING',
  UPLOADING: 'UPLOADING',
  PREPROCESSING: 'PREPROCESSING',
  OCR: 'OCR',
  EXTRACTION: 'EXTRACTION',
  VALIDATION: 'VALIDATION',
  CONFIDENCE_ANALYSIS: 'CONFIDENCE_ANALYSIS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  NEEDS_VERIFICATION: 'NEEDS_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SENT_BACK: 'SENT_BACK',
};

export const PIPELINE_STAGES = {
  UPLOAD: 'UPLOAD',
  PREPROCESSING: 'PREPROCESSING',
  OCR: 'OCR',
  EXTRACTION: 'EXTRACTION',
  VALIDATION: 'VALIDATION',
  CONFIDENCE_ANALYSIS: 'CONFIDENCE_ANALYSIS',
  COMPLETED: 'COMPLETED',
};

export const VERIFICATION_ACTIONS = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  SEND_BACK: 'SEND_BACK',
  UPDATE_FIELD: 'UPDATE_FIELD',
  NOTE_ADDED: 'NOTE_ADDED',
};

export const AUDIT_ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_CREATED: 'USER_CREATED',
  USER_STATUS_UPDATED: 'USER_STATUS_UPDATED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_PROCESS_TRIGGERED: 'DOCUMENT_PROCESS_TRIGGERED',
  LAND_RECORD_UPDATED: 'LAND_RECORD_UPDATED',
  LAND_RECORD_APPROVED: 'LAND_RECORD_APPROVED',
  LAND_RECORD_REJECTED: 'LAND_RECORD_REJECTED',
  LAND_RECORD_SENT_BACK: 'LAND_RECORD_SENT_BACK',
};

export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FILE_ERROR: 'FILE_ERROR',
  PIPELINE_ERROR: 'PIPELINE_ERROR',
  PROVIDER_UNCONFIGURED: 'PROVIDER_UNCONFIGURED',
  SERVER_ERROR: 'SERVER_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};
